import { Difficulty } from "@prisma/client";

type DemoQuestion = {
  text: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctOption: string;
  difficulty: Difficulty;
};

type DemoTopic = {
  name: string;
  questions: DemoQuestion[];
};

export type ItcDemoSubject = {
  courseCode: string;
  courseTitle: string;
  curriculumYear: number;
  topics: DemoTopic[];
};

function topicQuestions(questions: DemoQuestion[]): DemoTopic["questions"] {
  return questions;
}

/** IT Year 2 programming subjects — C++ (ITC 12) and Python (ITC 13). */
export const ITC_DEMO_SUBJECTS: ItcDemoSubject[] = [
  {
    courseCode: "ITC 12",
    courseTitle: "Computer Programming 1",
    curriculumYear: 1,
    topics: [
      {
        name: "Variables",
        questions: topicQuestions([
          {
            text: "[Demo] Which C++ statement correctly declares an integer variable named count?",
            optionA: "integer count;",
            optionB: "int count;",
            optionC: "var count = int;",
            optionD: "count: int;",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which operator assigns a value to a variable in C++?",
            optionA: "==",
            optionB: "=",
            optionC: ":=",
            optionD: "->",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] After `int x = 5; x += 3;`, what is the value of x?",
            optionA: "3",
            optionB: "5",
            optionC: "8",
            optionD: "53",
            correctOption: "C",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Which C++ type is best for storing a single character?",
            optionA: "string",
            optionB: "char",
            optionC: "bool",
            optionD: "double",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A variable declared inside a function block is visible:",
            optionA: "Throughout the entire program",
            optionB: "Only inside that block",
            optionC: "Only in main()",
            optionD: "In every function in the file",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Why use `const int MAX = 100;` instead of a plain int?",
            optionA: "const makes the variable global",
            optionB: "const prevents reassignment after initialization",
            optionC: "const converts the value to a string",
            optionD: "const is required for all integers",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Conditions",
        questions: topicQuestions([
          {
            text: "[Demo] Which C++ keyword starts a conditional branch?",
            optionA: "loop",
            optionB: "if",
            optionC: "switch",
            optionD: "case",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which expression evaluates to true when a equals b in C++?",
            optionA: "a = b",
            optionB: "a == b",
            optionC: "a === b",
            optionD: "a := b",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `else if` allow in a decision structure?",
            optionA: "Only one branch total",
            optionB: "Testing additional conditions after the first if",
            optionC: "Repeating code forever",
            optionD: "Declaring variables",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] In C++, which operator combines conditions so both must be true?",
            optionA: "||",
            optionB: "&&",
            optionC: "!",
            optionD: "|",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Given `int score = 75;`, which condition correctly checks for a passing score of at least 60?",
            optionA: "if (score > 60)",
            optionB: "if (score >= 60)",
            optionC: "if (score = 60)",
            optionD: "if (score == 60)",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] A nested if inside another if is most useful when:",
            optionA: "You need unrelated loops",
            optionB: "A second decision depends on the first being true",
            optionC: "You want to skip semicolons",
            optionD: "Variables must be global",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Loops",
        questions: topicQuestions([
          {
            text: "[Demo] Which C++ loop repeats while a condition is true and checks the condition first?",
            optionA: "for",
            optionB: "while",
            optionC: "do-while",
            optionD: "foreach",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] In `for (int i = 0; i < 5; i++)`, how many times does the body run?",
            optionA: "4",
            optionB: "5",
            optionC: "6",
            optionD: "0",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `i++` do inside a for loop?",
            optionA: "Decreases i by 1",
            optionB: "Increases i by 1",
            optionC: "Multiplies i by 2",
            optionD: "Resets i to 0",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A do-while loop differs from while because:",
            optionA: "It never runs the body",
            optionB: "It runs the body at least once",
            optionC: "It requires three expressions",
            optionD: "It cannot use a counter",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Which loop header prints values 1 through 10 inclusive?",
            optionA: "for (int i = 1; i < 10; i++)",
            optionB: "for (int i = 1; i <= 10; i++)",
            optionC: "for (int i = 0; i > 10; i++)",
            optionD: "for (int i = 10; i < 1; i++)",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] An infinite loop is most likely caused by:",
            optionA: "Updating the loop variable inside the body",
            optionB: "Never changing the condition toward false",
            optionC: "Using int instead of double",
            optionD: "Including iostream",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Arrays",
        questions: topicQuestions([
          {
            text: "[Demo] Which declares an integer array of size 5 in C++?",
            optionA: "int arr(5);",
            optionB: "int arr[5];",
            optionC: "array int[5] arr;",
            optionD: "int[] arr = 5;",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What is the index of the first element in a C++ array?",
            optionA: "1",
            optionB: "0",
            optionC: "-1",
            optionD: "Depends on size",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] If `int nums[4] = {10, 20, 30, 40};`, what is nums[2]?",
            optionA: "20",
            optionB: "30",
            optionC: "40",
            optionD: "2",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Accessing `arr[10]` when the array size is 5 causes:",
            optionA: "Automatic resizing",
            optionB: "Undefined behavior / out-of-bounds access",
            optionC: "A compile-time error always",
            optionD: "The value 0 always",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] To store a list of student scores that may grow, which is more flexible than a fixed array?",
            optionA: "A single char variable",
            optionB: "std::vector",
            optionC: "A bool flag",
            optionD: "A macro",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Iterating through every element of `int data[5]` safely requires indices:",
            optionA: "1 through 5",
            optionB: "0 through 4",
            optionC: "0 through 5",
            optionD: "5 through 0 only",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Functions",
        questions: topicQuestions([
          {
            text: "[Demo] Which keyword specifies the return type of a C++ function?",
            optionA: "return type appears before the function name",
            optionB: "function keyword only",
            optionC: "def",
            optionD: "proc",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `return 0;` typically mean in main()?",
            optionA: "Program failed",
            optionB: "Successful program termination",
            optionC: "Skip all loops",
            optionD: "Print zero only",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] A function parameter is:",
            optionA: "A value the function returns",
            optionB: "An input variable listed in the function definition",
            optionC: "A global constant",
            optionD: "A header file",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Which function signature returns nothing?",
            optionA: "int add(int a, int b)",
            optionB: "void greet(string name)",
            optionC: "double average(int x, int y)",
            optionD: "char grade(int score)",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Pass-by-value means the function receives:",
            optionA: "A copy of the argument",
            optionB: "The memory address only",
            optionC: "A reference alias always",
            optionD: "No data",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] A helper function that computes factorial is best designed to:",
            optionA: "Use global variables only",
            optionB: "Take input, compute, and return a result",
            optionC: "Never use return",
            optionD: "Print instead of returning for all callers",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "OOP",
        questions: topicQuestions([
          {
            text: "[Demo] In C++, a class groups:",
            optionA: "Only global variables",
            optionB: "Data members and member functions",
            optionC: "Preprocessor directives only",
            optionD: "Comments only",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] An object is:",
            optionA: "A blueprint for a class",
            optionB: "An instance of a class",
            optionC: "A header guard",
            optionD: "A loop counter",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which access specifier hides members from outside the class by default in a struct?",
            optionA: "private in struct",
            optionB: "public in struct",
            optionC: "protected only",
            optionD: "static only",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A constructor in C++ is called when:",
            optionA: "The program exits",
            optionB: "An object is created",
            optionC: "A file is included",
            optionD: "main returns",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Encapsulation means:",
            optionA: "Hiding implementation details behind a class interface",
            optionB: "Using only global functions",
            optionC: "Removing all private members",
            optionD: "Avoiding objects",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] If class `Student` has private `int id` and public `getId()`, this design:",
            optionA: "Breaks encapsulation",
            optionB: "Controls access to id through a method",
            optionC: "Makes id global",
            optionD: "Prevents object creation",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Algorithm",
        questions: topicQuestions([
          {
            text: "[Demo] An algorithm is best defined as:",
            optionA: "A programming language",
            optionB: "A step-by-step procedure to solve a problem",
            optionC: "A computer brand",
            optionD: "A syntax error",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Pseudocode is used to:",
            optionA: "Compile C++ directly",
            optionB: "Describe logic in plain structured steps",
            optionC: "Replace all testing",
            optionD: "Store binary files",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] To find the largest of three numbers, the first step is usually:",
            optionA: "Print hello world",
            optionB: "Read or receive the three values",
            optionC: "Delete the array",
            optionD: "Close the program",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Linear search checks elements:",
            optionA: "In random order only",
            optionB: "One by one until found or end",
            optionC: "Only the middle element",
            optionD: "Never compares values",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Bubble sort repeatedly:",
            optionA: "Deletes the smallest item",
            optionB: "Swaps adjacent out-of-order elements",
            optionC: "Uses recursion only",
            optionD: "Sorts without comparisons",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] An algorithm with O(n) time complexity means runtime grows:",
            optionA: "Linearly with input size",
            optionB: "Not at all with input size",
            optionC: "Exponentially always",
            optionD: "Only with compiler version",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
    ],
  },
  {
    courseCode: "ITC 13",
    courseTitle: "Computer Programming 2",
    curriculumYear: 1,
    topics: [
      {
        name: "Variables",
        questions: topicQuestions([
          {
            text: "[Demo] Which Python statement assigns 10 to variable x?",
            optionA: "x := 10",
            optionB: "x = 10",
            optionC: "int x = 10",
            optionD: "var x 10",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which is a valid Python variable name?",
            optionA: "2score",
            optionB: "score_total",
            optionC: "score-total",
            optionD: "class",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What is the type of `3.14` in Python?",
            optionA: "int",
            optionB: "float",
            optionC: "str",
            optionD: "bool",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] After `count = 4; count += 2`, what is count?",
            optionA: "42",
            optionB: "6",
            optionC: "2",
            optionD: "8",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] In Python, reassigning `name = \"Ana\"` to `name = \"Ben\"` shows that variables:",
            optionA: "Are fixed at compile time only",
            optionB: "Can refer to different values over time",
            optionC: "Must always be integers",
            optionD: "Cannot hold strings",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Using meaningful names like `student_count` instead of `x` improves:",
            optionA: "Syntax errors only",
            optionB: "Code readability and maintenance",
            optionC: "Python version number",
            optionD: "Memory size always",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Data Types",
        questions: topicQuestions([
          {
            text: "[Demo] Which Python literal is a list?",
            optionA: "(1, 2, 3)",
            optionB: "[1, 2, 3]",
            optionC: "{1, 2, 3}",
            optionD: "<1, 2, 3>",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which type represents True or False in Python?",
            optionA: "bool",
            optionB: "bit",
            optionC: "logic",
            optionD: "binary",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `len([10, 20, 30])` return?",
            optionA: "30",
            optionB: "3",
            optionC: "10",
            optionD: "6",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Which creates a dictionary mapping \"id\" to 101?",
            optionA: "{\"id\": 101}",
            optionB: "[\"id\", 101]",
            optionC: "(\"id\", 101)",
            optionD: "dict(id, 101)",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Slicing `text[1:4]` on `text = \"Python\"` returns:",
            optionA: "Pyt",
            optionB: "yth",
            optionC: "ytho",
            optionD: "hon",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] A tuple differs from a list because a tuple is:",
            optionA: "Mutable and ordered",
            optionB: "Immutable and ordered",
            optionC: "Unordered and mutable",
            optionD: "Always empty",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Conditions",
        questions: topicQuestions([
          {
            text: "[Demo] Which Python keyword starts a conditional?",
            optionA: "when",
            optionB: "if",
            optionC: "switch",
            optionD: "case",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which comparison checks equality in Python?",
            optionA: "=",
            optionB: "==",
            optionC: "===",
            optionD: ":=",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `elif` allow?",
            optionA: "Another condition after if/else chain",
            optionB: "Infinite loops only",
            optionC: "Importing modules",
            optionD: "Defining classes",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Which expression is True when age is at least 18?",
            optionA: "age > 18",
            optionB: "age >= 18",
            optionC: "age = 18",
            optionD: "age != 18",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] `if not logged_in:` runs its block when logged_in is:",
            optionA: "True",
            optionB: "False",
            optionC: "A string only",
            optionD: "Always skipped",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Chaining `if score >= 90: grade = 'A'` with lower thresholds is an example of:",
            optionA: "Multi-branch grading logic",
            optionB: "Exception handling",
            optionC: "List comprehension",
            optionD: "File I/O",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Loops",
        questions: topicQuestions([
          {
            text: "[Demo] Which Python loop iterates over each item in a list?",
            optionA: "for item in items:",
            optionB: "loop item from items:",
            optionC: "foreach item in items:",
            optionD: "repeat item in items:",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which loop repeats while a condition is true?",
            optionA: "for",
            optionB: "while",
            optionC: "do",
            optionD: "until",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `range(3)` produce?",
            optionA: "1, 2, 3",
            optionB: "0, 1, 2",
            optionC: "3, 2, 1",
            optionD: "0, 1, 2, 3",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] `break` inside a loop:",
            optionA: "Skips one iteration",
            optionB: "Exits the loop entirely",
            optionC: "Restarts Python",
            optionD: "Converts to a list",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A nested loop printing a multiplication table uses nested loops because:",
            optionA: "Each row needs iteration over columns",
            optionB: "Python forbids single loops",
            optionC: "while cannot print numbers",
            optionD: "range is unavailable",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] `continue` in a loop:",
            optionA: "Stops the entire program",
            optionB: "Skips to the next iteration",
            optionC: "Deletes the list",
            optionD: "Defines a function",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Functions",
        questions: topicQuestions([
          {
            text: "[Demo] Which keyword defines a function in Python?",
            optionA: "function",
            optionB: "def",
            optionC: "fn",
            optionD: "func",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] What does `return` do in a Python function?",
            optionA: "Imports a module",
            optionB: "Sends a value back to the caller",
            optionC: "Starts a loop",
            optionD: "Deletes parameters",
            correctOption: "B",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Calling `greet(\"Mia\")` passes \"Mia\" as:",
            optionA: "A return value",
            optionB: "An argument",
            optionC: "A global variable",
            optionD: "A module name",
            correctOption: "B",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A default parameter like `def show(msg=\"Hello\")` allows:",
            optionA: "Calling show() without arguments",
            optionB: "Only recursive calls",
            optionC: "No arguments ever",
            optionD: "Compile-time only binding",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A function that calculates average should:",
            optionA: "Modify unrelated globals only",
            optionB: "Accept inputs and return the computed average",
            optionC: "Never use return",
            optionD: "Print and crash",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Using `*args` in a function definition allows:",
            optionA: "A variable number of positional arguments",
            optionB: "Only keyword arguments",
            optionC: "No parameters",
            optionD: "Importing tkinter",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "Objects",
        questions: topicQuestions([
          {
            text: "[Demo] In Python, an object is created from:",
            optionA: "A class",
            optionB: "A comment",
            optionC: "A loop",
            optionD: "A shebang line",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Which creates a `Student` object?",
            optionA: "Student()",
            optionB: "new Student",
            optionC: "create Student",
            optionD: "object Student",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Instance attributes belong to:",
            optionA: "Each object individually",
            optionB: "Only the Python interpreter",
            optionC: "Comments in the file",
            optionD: "Import statements",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] `self` in a method refers to:",
            optionA: "The current instance",
            optionB: "The main module only",
            optionC: "A built-in function",
            optionD: "A random number",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Setting attributes in `__init__` ensures:",
            optionA: "Objects start with required state",
            optionB: "All methods become static",
            optionC: "The class cannot be reused",
            optionD: "GUI windows open automatically",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Two instances of the same class:",
            optionA: "Share the same attribute values always",
            optionB: "Can hold different attribute values",
            optionC: "Cannot call methods",
            optionD: "Are the same object",
            correctOption: "B",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "OOP",
        questions: topicQuestions([
          {
            text: "[Demo] A class in Python is:",
            optionA: "A blueprint for creating objects",
            optionB: "A type of loop",
            optionC: "A syntax error",
            optionD: "A GUI widget only",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Inheritance allows a child class to:",
            optionA: "Reuse and extend a parent class",
            optionB: "Delete all methods",
            optionC: "Avoid defining any attributes",
            optionD: "Run without objects",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] Method overriding means:",
            optionA: "A subclass provides its own version of a method",
            optionB: "Removing all parent methods",
            optionC: "Using only global functions",
            optionD: "Importing tkinter",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Encapsulation in Python often uses:",
            optionA: "Leading underscore naming conventions",
            optionB: "Deleting __init__",
            optionC: "Only tuples",
            optionD: "No attributes",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] If `Animal` defines `speak()` and `Dog` overrides it, calling `speak()` on a Dog object uses:",
            optionA: "Dog's implementation",
            optionB: "No method at all",
            optionC: "Only Animal's version always",
            optionD: "The main function",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Polymorphism lets code:",
            optionA: "Treat different object types through a common interface",
            optionB: "Avoid classes entirely",
            optionC: "Disable methods",
            optionD: "Run only in the shell",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
      {
        name: "GUI",
        questions: topicQuestions([
          {
            text: "[Demo] Which Python module is commonly used for basic GUI windows?",
            optionA: "tkinter",
            optionB: "sqlite3",
            optionC: "math",
            optionD: "os",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] In tkinter, the main window is usually created with:",
            optionA: "Tk()",
            optionB: "Window.new()",
            optionC: "GUI()",
            optionD: "Form()",
            correctOption: "A",
            difficulty: Difficulty.EASY,
          },
          {
            text: "[Demo] `mainloop()` in tkinter:",
            optionA: "Starts the event loop for the window",
            optionB: "Deletes all widgets",
            optionC: "Compiles Python to C",
            optionD: "Closes the terminal",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] A Button widget in tkinter typically needs:",
            optionA: "A parent container and a command callback",
            optionB: "Only a print statement",
            optionC: "A SQL query",
            optionD: "A class inheritance chain",
            correctOption: "A",
            difficulty: Difficulty.MEDIUM,
          },
          {
            text: "[Demo] Packing widgets with `.pack()` organizes them:",
            optionA: "According to pack geometry rules in the parent",
            optionB: "Randomly on every click",
            optionC: "Only in separate processes",
            optionD: "Without a parent window",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
          {
            text: "[Demo] Separating GUI layout code from business logic helps:",
            optionA: "Make the program easier to test and maintain",
            optionB: "Prevent all user input",
            optionC: "Remove event handling",
            optionD: "Disable the main loop",
            correctOption: "A",
            difficulty: Difficulty.HARD,
          },
        ]),
      },
    ],
  },
];
